spring:
  application:
    name: rab

  datasource:
    url: jdbc:mysql://localhost:13306/rab?useSSL=false&allowPublicKeyRetrieval=true&connectionTimeZone=Asia/Seoul&forceConnectionTimeZoneToSession=true
    username: rab
    password: rab1234

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        query:
          translator: com.querydsl.jpa.impl.JPAQueryTranslator
    show-sql: true
    defer-datasource-initialization: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  port: 25000
